export { default as map } from './map'
export { default as filter } from './filter'
export { default as reduce } from './reduce'
export { default as compose } from './compose'
export { default as curryN } from './_curry'
